---
- name: urotaxiplaybook
  hosts: all
  become: yes
  become_method: sudo
  vars:
    TOMCAT_DOWNLOAD_URL: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.86/bin/apache-tomcat-9.0.86.tar.gz"
    TOMCAT_HOME_DIR: "/u01/middleware/apache-tomcat-9.0.86"
  tasks:
    - name: install jdk ********************************
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: create middleware directory*****************************
      file:
        path: /u01/middleware
        state: directory
        owner: ubuntu
        group: ubuntu
      become: yes
      become_method: sudo
    - name: download tomcat9 ****************************
      get_url:
        url: "{{TOMCAT_DOWNLOAD_URL}}"
        dest: /u01/middleware/
    - name: unzip tomcat ************************************
      unarchive:
        src: /u01/middleware/apache-tomcat-9.0.86.tar.gz
        dest: /u01/middleware
        remote_src: true
    - name: JAVA_HOME **********************************
      shell: readlink -f $(which java) | sed 's/bin.*//g'
      register: JDK_HOME
    - name: install tomcat as a service*******************
      template:
        src: src/main/config/ansible/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      notify:
        - tomcatreload
    - name: create schema *********************************
      community.mysql.mysql_db:
        state: import
        name: all
        target: ../db/urotaxidb.sql
        login_host: "{{ lookup('env','DB_HOST') }}"
        login_user: "{{ lookup('env','UROTAXI_DB_USER') }}"
        login_password: "{{ lookup('env','UROTAXI_DB_PSW') }}"
    - name: deploy ***********************************
      copy:
        src: ../target/urotaxi.war
        dest: /u01/middleware/apache-tomcat-9.0.86/webapps/
      notify:
        - tomcatrestart
  handlers:
    - name: tomcatreload *********************************
      service:
        name: tomcat
        state: reloaded
        enabled: true
        daemon_reload: true
      become: yes
      become_method: sudo
    - name: restart ********************************
      service:
        name: tomcatrestart
        state: restart
        become: yes
        become_method: sudo
